name: La Hanau
favicon: null
layout_spectrum: 0.9572153962217271
typography_spectrum: 0.23130699340254068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6788555302191526
  lightness: 0.658871810650453
  saturation: 0.5244006228167564
  rhythmicContrast: 0.5230528949759901
purpose: []
