name: Pumehana
favicon: null
layout_spectrum: 0.26148
typography_spectrum: 0.23130699340254068
title: Pumehana
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c0b8cc'
    - '#9990aa'
    - '#512c11'
    - '#e6e2e9'
  brandStrength: 1
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 1
purpose: []
