name: Prayana
favicon: null
layout_spectrum: 0.80977
typography_spectrum: 0.81075
title: Prayana more
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e3a02b'
    - '#d37b00'
    - '#280000'
    - '#813f00'
    - '#790000'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
